name: generate animation

on:
  # schedule:
  #   - cron: "0 */6 * * *" # every 6 hours
  push

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate github-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: leozzmc
          svg_out_path: dist/github-snake.svg
  
