name: generate animation

on:
  # schedule:
  #   - cron: "0 */6 * * *" # every 6 hours
  push

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate github-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: leozzmc
          svg_out_path: dist/github-snake.svg
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
